
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file AdminUsers.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace QUANLYQN.Entities
{
	///<summary>
	/// An object representation of the 'ADMIN_USERS' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class AdminUsersBase : EntityBase, QUANLYQN.Entities.IAdminUsers, IEntityId<AdminUsersKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private AdminUsersEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private AdminUsersEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private AdminUsersEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<AdminUsers> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event AdminUsersEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event AdminUsersEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="AdminUsersBase"/> instance.
		///</summary>
		public AdminUsersBase()
		{
			this.entityData = new AdminUsersEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="AdminUsersBase"/> instance.
		///</summary>
		///<param name="idUser"></param>
		///<param name="password"></param>
		///<param name="fullName"></param>
		///<param name="active"></param>
		///<param name="modified"></param>
		///<param name="description"></param>
		public AdminUsersBase(System.String idUser, System.Byte[] password, System.String fullName, 
			System.Int32? active, System.DateTime? modified, System.String description)
		{
			this.entityData = new AdminUsersEntityData();
			this.backupData = null;

			this.IdUser = idUser;
			this.Password = password;
			this.FullName = fullName;
			this.Active = active;
			this.Modified = modified;
			this.Description = description;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="AdminUsers"/> instance.
		///</summary>
		///<param name="idUser"></param>
		///<param name="password"></param>
		///<param name="fullName"></param>
		///<param name="active"></param>
		///<param name="modified"></param>
		///<param name="description"></param>
		public static AdminUsers CreateAdminUsers(System.String idUser, System.Byte[] password, System.String fullName, 
			System.Int32? active, System.DateTime? modified, System.String description)
		{
			AdminUsers newAdminUsers = new AdminUsers();
			newAdminUsers.IdUser = idUser;
			newAdminUsers.Password = password;
			newAdminUsers.FullName = fullName;
			newAdminUsers.Active = active;
			newAdminUsers.Modified = modified;
			newAdminUsers.Description = description;
			return newAdminUsers;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdUser property. 
		///		
		/// </summary>
		/// <value>This type is char.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 15)]
		public virtual System.String IdUser
		{
			get
			{
				return this.entityData.IdUser; 
			}
			
			set
			{
				if (this.entityData.IdUser == value)
					return;
					
				OnColumnChanging(AdminUsersColumn.IdUser, this.entityData.IdUser);
				this.entityData.IdUser = value;
				this.EntityId.IdUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AdminUsersColumn.IdUser, this.entityData.IdUser);
				OnPropertyChanged("IdUser");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ID_USER property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the ID_USER property.</remarks>
		/// <value>This type is char</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalIdUser
		{
			get { return this.entityData.OriginalIdUser; }
			set { this.entityData.OriginalIdUser = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Password property. 
		///		
		/// </summary>
		/// <value>This type is varbinary.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Byte[] Password
		{
			get
			{
				return this.entityData.Password; 
			}
			
			set
			{
				if (this.entityData.Password == value)
					return;
					
				OnColumnChanging(AdminUsersColumn.Password, this.entityData.Password);
				this.entityData.Password = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AdminUsersColumn.Password, this.entityData.Password);
				OnPropertyChanged("Password");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FullName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 255)]
		public virtual System.String FullName
		{
			get
			{
				return this.entityData.FullName; 
			}
			
			set
			{
				if (this.entityData.FullName == value)
					return;
					
				OnColumnChanging(AdminUsersColumn.FullName, this.entityData.FullName);
				this.entityData.FullName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AdminUsersColumn.FullName, this.entityData.FullName);
				OnPropertyChanged("FullName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Active property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsActiveNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? Active
		{
			get
			{
				return this.entityData.Active; 
			}
			
			set
			{
				if (this.entityData.Active == value)
					return;
					
				OnColumnChanging(AdminUsersColumn.Active, this.entityData.Active);
				this.entityData.Active = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AdminUsersColumn.Active, this.entityData.Active);
				OnPropertyChanged("Active");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Modified property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsModifiedNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? Modified
		{
			get
			{
				return this.entityData.Modified; 
			}
			
			set
			{
				if (this.entityData.Modified == value)
					return;
					
				OnColumnChanging(AdminUsersColumn.Modified, this.entityData.Modified);
				this.entityData.Modified = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AdminUsersColumn.Modified, this.entityData.Modified);
				OnPropertyChanged("Modified");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
					
				OnColumnChanging(AdminUsersColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AdminUsersColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections

		/// <summary>
		///	Holds a collection of AdminGroupsFromAdminGroupusers objects
		///	which are related to this object through the junction table AdminGroupusers
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<AdminGroups> AdminGroupsCollection_From_AdminGroupusers
		{
			get { return entityData.AdminGroupsCollection_From_AdminGroupusers; }
			set { entityData.AdminGroupsCollection_From_AdminGroupusers = value; }	
		}
	
		/// <summary>
		///	Holds a collection of AdminGroupusers objects
		///	which are related to this object through the relation FK_ADMIN_GROUPUSERS_ADMIN_USERS
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<AdminGroupusers> AdminGroupusersCollection
		{
			get { return entityData.AdminGroupusersCollection; }
			set { entityData.AdminGroupusersCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("IdUser", "Id User"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("IdUser", "Id User", 15));
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("Password", "Password"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("FullName", "Full Name", 255));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("Description", "Description", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "ADMIN_USERS"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID_USER", "PASSWORD", "FULL_NAME", "ACTIVE", "MODIFIED", "DESCRIPTION"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as AdminUsersEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (AdminUsers) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<AdminUsers>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as AdminUsers);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed AdminUsers Entity 
		///</summary>
		public virtual AdminUsers Copy()
		{
			//shallow copy entity
			AdminUsers copy = new AdminUsers();
			copy.SuppressEntityEvents = true;
			copy.IdUser = this.IdUser;
			copy.OriginalIdUser = this.OriginalIdUser;
			copy.Password = this.Password;
			copy.FullName = this.FullName;
			copy.Active = this.Active;
			copy.Modified = this.Modified;
			copy.Description = this.Description;
			
		
			//deep copy nested objects
			copy.AdminGroupsCollection_From_AdminGroupusers = (TList<AdminGroups>) MakeCopyOf(this.AdminGroupsCollection_From_AdminGroupusers); 
			copy.AdminGroupusersCollection = (TList<AdminGroupusers>) MakeCopyOf(this.AdminGroupusersCollection); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed AdminUsers Entity which is a deep copy of the current entity.
		///</summary>
		public virtual AdminUsers DeepCopy()
		{
			return EntityHelper.Clone<AdminUsers>(this as AdminUsers);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as AdminUsersEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as AdminUsersEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(AdminUsersColumn column)
		{
			switch(column)
			{
					case AdminUsersColumn.IdUser:
					return entityData.IdUser != _originalData.IdUser;
					case AdminUsersColumn.Password:
					return entityData.Password != _originalData.Password;
					case AdminUsersColumn.FullName:
					return entityData.FullName != _originalData.FullName;
					case AdminUsersColumn.Active:
					return entityData.Active != _originalData.Active;
					case AdminUsersColumn.Modified:
					return entityData.Modified != _originalData.Modified;
					case AdminUsersColumn.Description:
					return entityData.Description != _originalData.Description;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdUser != _originalData.IdUser;
			result = result || entityData.Password != _originalData.Password;
			result = result || entityData.FullName != _originalData.FullName;
			result = result || entityData.Active != _originalData.Active;
			result = result || entityData.Modified != _originalData.Modified;
			result = result || entityData.Description != _originalData.Description;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="AdminUsersBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is AdminUsersBase)
				return Equals(this, (AdminUsersBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="AdminUsersBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdUser.GetHashCode() ^ 
					this.Password.GetHashCode() ^ 
					((this.FullName == null) ? string.Empty : this.FullName.ToString()).GetHashCode() ^ 
					((this.Active == null) ? string.Empty : this.Active.ToString()).GetHashCode() ^ 
					((this.Modified == null) ? string.Empty : this.Modified.ToString()).GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="AdminUsersBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(AdminUsersBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="AdminUsersBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="AdminUsersBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="AdminUsersBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(AdminUsersBase Object1, AdminUsersBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdUser != Object2.IdUser)
				equal = false;
			if (Object1.Password != Object2.Password)
				equal = false;
			if ( Object1.FullName != null && Object2.FullName != null )
			{
				if (Object1.FullName != Object2.FullName)
					equal = false;
			}
			else if (Object1.FullName == null ^ Object2.FullName == null )
			{
				equal = false;
			}
			if ( Object1.Active != null && Object2.Active != null )
			{
				if (Object1.Active != Object2.Active)
					equal = false;
			}
			else if (Object1.Active == null ^ Object2.Active == null )
			{
				equal = false;
			}
			if ( Object1.Modified != null && Object2.Modified != null )
			{
				if (Object1.Modified != Object2.Modified)
					equal = false;
			}
			else if (Object1.Modified == null ^ Object2.Modified == null )
			{
				equal = false;
			}
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((AdminUsersBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static AdminUsersComparer GetComparer()
        {
            return new AdminUsersComparer();
        }
        */

        // Comparer delegates back to AdminUsers
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(AdminUsers rhs, AdminUsersColumn which)
        {
            switch (which)
            {
            	
            	
            	case AdminUsersColumn.IdUser:
            		return this.IdUser.CompareTo(rhs.IdUser);
            		
            		                 
            	
            		                 
            	
            	
            	case AdminUsersColumn.FullName:
            		return this.FullName.CompareTo(rhs.FullName);
            		
            		                 
            	
            	
            	case AdminUsersColumn.Active:
            		return this.Active.Value.CompareTo(rhs.Active.Value);
            		
            		                 
            	
            	
            	case AdminUsersColumn.Modified:
            		return this.Modified.Value.CompareTo(rhs.Modified.Value);
            		
            		                 
            	
            	
            	case AdminUsersColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<AdminUsersKey> Members
		
		// member variable for the EntityId property
		private AdminUsersKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual AdminUsersKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new AdminUsersKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("AdminUsers")
					.Append("|").Append( this.IdUser.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- IdUser: {0}{6}- Password: {1}{6}- FullName: {2}{6}- Active: {3}{6}- Modified: {4}{6}- Description: {5}{6}", 
				this.IdUser,
				this.Password,
				(this.FullName == null) ? string.Empty : this.FullName.ToString(),
				(this.Active == null) ? string.Empty : this.Active.ToString(),
				(this.Modified == null) ? string.Empty : this.Modified.ToString(),
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'ADMIN_USERS' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class AdminUsersEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID_USER : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "ADMIN_USERS"</remarks>
			public System.String IdUser;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.String OriginalIdUser;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// PASSWORD : 
		/// </summary>
		public System.Byte[]		  Password = new byte[] {};
		
		/// <summary>
		/// FULL_NAME : 
		/// </summary>
		public System.String		  FullName = null;
		
		/// <summary>
		/// ACTIVE : 
		/// </summary>
		public System.Int32?		  Active = null;
		
		/// <summary>
		/// MODIFIED : 
		/// </summary>
		public System.DateTime?		  Modified = null;
		
		/// <summary>
		/// DESCRIPTION : 
		/// </summary>
		public System.String		  Description = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region AdminGroupsCollection_From_AdminGroupusers
		
		private TList<AdminGroups> adminGroupsCollectionFromAdminGroupusers;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table adminGroupsCollectionFromAdminGroupusers
		/// </summary>	
		public TList<AdminGroups> AdminGroupsCollection_From_AdminGroupusers
		{
			get
			{
				if (adminGroupsCollectionFromAdminGroupusers == null)
				{
				adminGroupsCollectionFromAdminGroupusers = new TList<AdminGroups>();
				}
	
				return adminGroupsCollectionFromAdminGroupusers;
			}
			set { adminGroupsCollectionFromAdminGroupusers = value; }
		}
		
		#endregion 

		#region AdminGroupusersCollection
		
		private TList<AdminGroupusers> adminGroupusersIdUser;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation adminGroupusersIdUser
		/// </summary>	
		public TList<AdminGroupusers> AdminGroupusersCollection
		{
			get
			{
				if (adminGroupusersIdUser == null)
				{
				adminGroupusersIdUser = new TList<AdminGroupusers>();
				}
	
				return adminGroupusersIdUser;
			}
			set { adminGroupusersIdUser = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			AdminUsersEntityData _tmp = new AdminUsersEntityData();
						
			_tmp.IdUser = this.IdUser;
			_tmp.OriginalIdUser = this.OriginalIdUser;
			
			_tmp.Password = this.Password;
			_tmp.FullName = this.FullName;
			_tmp.Active = this.Active;
			_tmp.Modified = this.Modified;
			_tmp.Description = this.Description;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this.adminGroupsCollectionFromAdminGroupusers != null)
				_tmp.AdminGroupsCollection_From_AdminGroupusers = (TList<AdminGroups>) MakeCopyOf(this.AdminGroupsCollection_From_AdminGroupusers); 
			if (this.adminGroupusersIdUser != null)
				_tmp.AdminGroupusersCollection = (TList<AdminGroupusers>) MakeCopyOf(this.AdminGroupusersCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AdminUsersColumn"/> which has raised the event.</param>
		public void OnColumnChanging(AdminUsersColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AdminUsersColumn"/> which has raised the event.</param>
		public void OnColumnChanged(AdminUsersColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AdminUsersColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(AdminUsersColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				AdminUsersEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new AdminUsersEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AdminUsersColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(AdminUsersColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				AdminUsersEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new AdminUsersEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region AdminUsersEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="AdminUsers"/> object.
	/// </remarks>
	public class AdminUsersEventArgs : System.EventArgs
	{
		private AdminUsersColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the AdminUsersEventArgs class.
		///</summary>
		public AdminUsersEventArgs(AdminUsersColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the AdminUsersEventArgs class.
		///</summary>
		public AdminUsersEventArgs(AdminUsersColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The AdminUsersColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="AdminUsersColumn" />
		public AdminUsersColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all AdminUsers related events.
	///</summary>
	public delegate void AdminUsersEventHandler(object sender, AdminUsersEventArgs e);
	
	#region AdminUsersComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class AdminUsersComparer : System.Collections.Generic.IComparer<AdminUsers>
	{
		AdminUsersColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:AdminUsersComparer"/> class.
        /// </summary>
		public AdminUsersComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:AdminUsersComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public AdminUsersComparer(AdminUsersColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="AdminUsers"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="AdminUsers"/> to compare.</param>
        /// <param name="b">The second <c>AdminUsers</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(AdminUsers a, AdminUsers b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(AdminUsers entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(AdminUsers a, AdminUsers b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public AdminUsersColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region AdminUsersKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="AdminUsers"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class AdminUsersKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the AdminUsersKey class.
		/// </summary>
		public AdminUsersKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the AdminUsersKey class.
		/// </summary>
		public AdminUsersKey(AdminUsersBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdUser = entity.IdUser;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the AdminUsersKey class.
		/// </summary>
		public AdminUsersKey(System.String idUser)
		{
			#region Init Properties

			this.IdUser = idUser;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private AdminUsersBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public AdminUsersBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdUser property
		private System.String _idUser;
		
		/// <summary>
		/// Gets or sets the IdUser property.
		/// </summary>
		public System.String IdUser
		{
			get { return _idUser; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdUser = value;
				
				_idUser = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdUser = ( values["IdUser"] != null ) ? (System.String) EntityUtil.ChangeType(values["IdUser"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdUser", IdUser);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdUser: {0}{1}",
								IdUser,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region AdminUsersColumn Enum
	
	/// <summary>
	/// Enumerate the AdminUsers columns.
	/// </summary>
	[Serializable]
	public enum AdminUsersColumn : int
	{
		/// <summary>
		/// IdUser : 
		/// </summary>
		[EnumTextValue("ID_USER")]
		[ColumnEnum("ID_USER", typeof(System.String), System.Data.DbType.AnsiStringFixedLength, true, false, false, 15)]
		IdUser = 1,
		/// <summary>
		/// Password : 
		/// </summary>
		[EnumTextValue("PASSWORD")]
		[ColumnEnum("PASSWORD", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, false)]
		Password = 2,
		/// <summary>
		/// FullName : 
		/// </summary>
		[EnumTextValue("FULL_NAME")]
		[ColumnEnum("FULL_NAME", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		FullName = 3,
		/// <summary>
		/// Active : 
		/// </summary>
		[EnumTextValue("ACTIVE")]
		[ColumnEnum("ACTIVE", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		Active = 4,
		/// <summary>
		/// Modified : 
		/// </summary>
		[EnumTextValue("MODIFIED")]
		[ColumnEnum("MODIFIED", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		Modified = 5,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("DESCRIPTION")]
		[ColumnEnum("DESCRIPTION", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		Description = 6
	}//End enum

	#endregion AdminUsersColumn Enum

} // end namespace
