
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Dmlop.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace QUANLYQN.Entities
{
	///<summary>
	/// An object representation of the 'DMLOP' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class DmlopBase : EntityBase, QUANLYQN.Entities.IDmlop, IEntityId<DmlopKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private DmlopEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private DmlopEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private DmlopEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Dmlop> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event DmlopEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DmlopEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="DmlopBase"/> instance.
		///</summary>
		public DmlopBase()
		{
			this.entityData = new DmlopEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="DmlopBase"/> instance.
		///</summary>
		///<param name="malop"></param>
		///<param name="tenlop"></param>
		///<param name="idDaidoi"></param>
		///<param name="ghichu"></param>
		public DmlopBase(System.String malop, System.String tenlop, System.Int32 idDaidoi, 
			System.String ghichu)
		{
			this.entityData = new DmlopEntityData();
			this.backupData = null;

			this.Malop = malop;
			this.Tenlop = tenlop;
			this.IdDaidoi = idDaidoi;
			this.Ghichu = ghichu;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Dmlop"/> instance.
		///</summary>
		///<param name="malop"></param>
		///<param name="tenlop"></param>
		///<param name="idDaidoi"></param>
		///<param name="ghichu"></param>
		public static Dmlop CreateDmlop(System.String malop, System.String tenlop, System.Int32 idDaidoi, 
			System.String ghichu)
		{
			Dmlop newDmlop = new Dmlop();
			newDmlop.Malop = malop;
			newDmlop.Tenlop = tenlop;
			newDmlop.IdDaidoi = idDaidoi;
			newDmlop.Ghichu = ghichu;
			return newDmlop;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdLop property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 IdLop
		{
			get
			{
				return this.entityData.IdLop; 
			}
			
			set
			{
				if (this.entityData.IdLop == value)
					return;
					
				OnColumnChanging(DmlopColumn.IdLop, this.entityData.IdLop);
				this.entityData.IdLop = value;
				this.EntityId.IdLop = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DmlopColumn.IdLop, this.entityData.IdLop);
				OnPropertyChanged("IdLop");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Malop property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String Malop
		{
			get
			{
				return this.entityData.Malop; 
			}
			
			set
			{
				if (this.entityData.Malop == value)
					return;
					
				OnColumnChanging(DmlopColumn.Malop, this.entityData.Malop);
				this.entityData.Malop = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DmlopColumn.Malop, this.entityData.Malop);
				OnPropertyChanged("Malop");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Tenlop property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String Tenlop
		{
			get
			{
				return this.entityData.Tenlop; 
			}
			
			set
			{
				if (this.entityData.Tenlop == value)
					return;
					
				OnColumnChanging(DmlopColumn.Tenlop, this.entityData.Tenlop);
				this.entityData.Tenlop = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DmlopColumn.Tenlop, this.entityData.Tenlop);
				OnPropertyChanged("Tenlop");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdDaidoi property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 IdDaidoi
		{
			get
			{
				return this.entityData.IdDaidoi; 
			}
			
			set
			{
				if (this.entityData.IdDaidoi == value)
					return;
					
				OnColumnChanging(DmlopColumn.IdDaidoi, this.entityData.IdDaidoi);
				this.entityData.IdDaidoi = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DmlopColumn.IdDaidoi, this.entityData.IdDaidoi);
				OnPropertyChanged("IdDaidoi");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Ghichu property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String Ghichu
		{
			get
			{
				return this.entityData.Ghichu; 
			}
			
			set
			{
				if (this.entityData.Ghichu == value)
					return;
					
				OnColumnChanging(DmlopColumn.Ghichu, this.entityData.Ghichu);
				this.entityData.Ghichu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DmlopColumn.Ghichu, this.entityData.Ghichu);
				OnPropertyChanged("Ghichu");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Dmdonvi"/>.
		/// </summary>
		/// <value>The source Dmdonvi for IdDaidoi.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Dmdonvi IdDaidoiSource
      	{
            get { return entityData.IdDaidoiSource; }
            set { entityData.IdDaidoiSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Quannhan objects
		///	which are related to this object through the relation FK_QUANNHAN_DMLOP
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Quannhan> QuannhanCollection
		{
			get { return entityData.QuannhanCollection; }
			set { entityData.QuannhanCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("Malop", "Malop"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("Malop", "Malop", 50));
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("Tenlop", "Tenlop"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("Tenlop", "Tenlop", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "DMLOP"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID_LOP", "MALOP", "TENLOP", "ID_DAIDOI", "GHICHU"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as DmlopEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Dmlop) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Dmlop>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Dmlop);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Dmlop Entity 
		///</summary>
		public virtual Dmlop Copy()
		{
			//shallow copy entity
			Dmlop copy = new Dmlop();
			copy.SuppressEntityEvents = true;
			copy.IdLop = this.IdLop;
			copy.Malop = this.Malop;
			copy.Tenlop = this.Tenlop;
			copy.IdDaidoi = this.IdDaidoi;
			copy.Ghichu = this.Ghichu;
			
			copy.IdDaidoiSource = MakeCopyOf(this.IdDaidoiSource) as Dmdonvi;
		
			//deep copy nested objects
			copy.QuannhanCollection = (TList<Quannhan>) MakeCopyOf(this.QuannhanCollection); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed Dmlop Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Dmlop DeepCopy()
		{
			return EntityHelper.Clone<Dmlop>(this as Dmlop);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as DmlopEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as DmlopEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(DmlopColumn column)
		{
			switch(column)
			{
					case DmlopColumn.IdLop:
					return entityData.IdLop != _originalData.IdLop;
					case DmlopColumn.Malop:
					return entityData.Malop != _originalData.Malop;
					case DmlopColumn.Tenlop:
					return entityData.Tenlop != _originalData.Tenlop;
					case DmlopColumn.IdDaidoi:
					return entityData.IdDaidoi != _originalData.IdDaidoi;
					case DmlopColumn.Ghichu:
					return entityData.Ghichu != _originalData.Ghichu;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdLop != _originalData.IdLop;
			result = result || entityData.Malop != _originalData.Malop;
			result = result || entityData.Tenlop != _originalData.Tenlop;
			result = result || entityData.IdDaidoi != _originalData.IdDaidoi;
			result = result || entityData.Ghichu != _originalData.Ghichu;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="DmlopBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is DmlopBase)
				return Equals(this, (DmlopBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="DmlopBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdLop.GetHashCode() ^ 
					this.Malop.GetHashCode() ^ 
					this.Tenlop.GetHashCode() ^ 
					this.IdDaidoi.GetHashCode() ^ 
					((this.Ghichu == null) ? string.Empty : this.Ghichu.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="DmlopBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(DmlopBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="DmlopBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="DmlopBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="DmlopBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(DmlopBase Object1, DmlopBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdLop != Object2.IdLop)
				equal = false;
			if (Object1.Malop != Object2.Malop)
				equal = false;
			if (Object1.Tenlop != Object2.Tenlop)
				equal = false;
			if (Object1.IdDaidoi != Object2.IdDaidoi)
				equal = false;
			if ( Object1.Ghichu != null && Object2.Ghichu != null )
			{
				if (Object1.Ghichu != Object2.Ghichu)
					equal = false;
			}
			else if (Object1.Ghichu == null ^ Object2.Ghichu == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((DmlopBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static DmlopComparer GetComparer()
        {
            return new DmlopComparer();
        }
        */

        // Comparer delegates back to Dmlop
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Dmlop rhs, DmlopColumn which)
        {
            switch (which)
            {
            	
            	
            	case DmlopColumn.IdLop:
            		return this.IdLop.CompareTo(rhs.IdLop);
            		
            		                 
            	
            	
            	case DmlopColumn.Malop:
            		return this.Malop.CompareTo(rhs.Malop);
            		
            		                 
            	
            	
            	case DmlopColumn.Tenlop:
            		return this.Tenlop.CompareTo(rhs.Tenlop);
            		
            		                 
            	
            	
            	case DmlopColumn.IdDaidoi:
            		return this.IdDaidoi.CompareTo(rhs.IdDaidoi);
            		
            		                 
            	
            	
            	case DmlopColumn.Ghichu:
            		return this.Ghichu.CompareTo(rhs.Ghichu);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<DmlopKey> Members
		
		// member variable for the EntityId property
		private DmlopKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual DmlopKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new DmlopKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Dmlop")
					.Append("|").Append( this.IdLop.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- IdLop: {0}{5}- Malop: {1}{5}- Tenlop: {2}{5}- IdDaidoi: {3}{5}- Ghichu: {4}{5}", 
				this.IdLop,
				this.Malop,
				this.Tenlop,
				this.IdDaidoi,
				(this.Ghichu == null) ? string.Empty : this.Ghichu.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'DMLOP' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class DmlopEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID_LOP : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "DMLOP"</remarks>
			public System.Int32 IdLop;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// MALOP : 
		/// </summary>
		public System.String		  Malop = string.Empty;
		
		/// <summary>
		/// TENLOP : 
		/// </summary>
		public System.String		  Tenlop = string.Empty;
		
		/// <summary>
		/// ID_DAIDOI : 
		/// </summary>
		public System.Int32		  IdDaidoi = (int)0;
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		public System.String		  Ghichu = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Dmdonvi _idDaidoiSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Dmdonvi"/>.
		/// </summary>
		/// <value>The source Dmdonvi for IdDaidoi.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Dmdonvi IdDaidoiSource
      	{
            get { return this._idDaidoiSource; }
            set { this._idDaidoiSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region QuannhanCollection
		
		private TList<Quannhan> quannhanIdLop;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation quannhanIdLop
		/// </summary>	
		public TList<Quannhan> QuannhanCollection
		{
			get
			{
				if (quannhanIdLop == null)
				{
				quannhanIdLop = new TList<Quannhan>();
				}
	
				return quannhanIdLop;
			}
			set { quannhanIdLop = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			DmlopEntityData _tmp = new DmlopEntityData();
						
			_tmp.IdLop = this.IdLop;
			
			_tmp.Malop = this.Malop;
			_tmp.Tenlop = this.Tenlop;
			_tmp.IdDaidoi = this.IdDaidoi;
			_tmp.Ghichu = this.Ghichu;
			
			#region Source Parent Composite Entities
			if (this.IdDaidoiSource != null)
				_tmp.IdDaidoiSource = MakeCopyOf(this.IdDaidoiSource) as Dmdonvi;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this.quannhanIdLop != null)
				_tmp.QuannhanCollection = (TList<Quannhan>) MakeCopyOf(this.QuannhanCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DmlopColumn"/> which has raised the event.</param>
		public void OnColumnChanging(DmlopColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DmlopColumn"/> which has raised the event.</param>
		public void OnColumnChanged(DmlopColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DmlopColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(DmlopColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				DmlopEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new DmlopEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DmlopColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(DmlopColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				DmlopEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new DmlopEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region DmlopEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Dmlop"/> object.
	/// </remarks>
	public class DmlopEventArgs : System.EventArgs
	{
		private DmlopColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the DmlopEventArgs class.
		///</summary>
		public DmlopEventArgs(DmlopColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the DmlopEventArgs class.
		///</summary>
		public DmlopEventArgs(DmlopColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The DmlopColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="DmlopColumn" />
		public DmlopColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Dmlop related events.
	///</summary>
	public delegate void DmlopEventHandler(object sender, DmlopEventArgs e);
	
	#region DmlopComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class DmlopComparer : System.Collections.Generic.IComparer<Dmlop>
	{
		DmlopColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:DmlopComparer"/> class.
        /// </summary>
		public DmlopComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:DmlopComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public DmlopComparer(DmlopColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Dmlop"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Dmlop"/> to compare.</param>
        /// <param name="b">The second <c>Dmlop</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Dmlop a, Dmlop b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Dmlop entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Dmlop a, Dmlop b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public DmlopColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region DmlopKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Dmlop"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class DmlopKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DmlopKey class.
		/// </summary>
		public DmlopKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the DmlopKey class.
		/// </summary>
		public DmlopKey(DmlopBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdLop = entity.IdLop;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the DmlopKey class.
		/// </summary>
		public DmlopKey(System.Int32 idLop)
		{
			#region Init Properties

			this.IdLop = idLop;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private DmlopBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public DmlopBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdLop property
		private System.Int32 _idLop;
		
		/// <summary>
		/// Gets or sets the IdLop property.
		/// </summary>
		public System.Int32 IdLop
		{
			get { return _idLop; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdLop = value;
				
				_idLop = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdLop = ( values["IdLop"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["IdLop"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdLop", IdLop);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdLop: {0}{1}",
								IdLop,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region DmlopColumn Enum
	
	/// <summary>
	/// Enumerate the Dmlop columns.
	/// </summary>
	[Serializable]
	public enum DmlopColumn : int
	{
		/// <summary>
		/// IdLop : 
		/// </summary>
		[EnumTextValue("ID_LOP")]
		[ColumnEnum("ID_LOP", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		IdLop = 1,
		/// <summary>
		/// Malop : 
		/// </summary>
		[EnumTextValue("MALOP")]
		[ColumnEnum("MALOP", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Malop = 2,
		/// <summary>
		/// Tenlop : 
		/// </summary>
		[EnumTextValue("TENLOP")]
		[ColumnEnum("TENLOP", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Tenlop = 3,
		/// <summary>
		/// IdDaidoi : 
		/// </summary>
		[EnumTextValue("ID_DAIDOI")]
		[ColumnEnum("ID_DAIDOI", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		IdDaidoi = 4,
		/// <summary>
		/// Ghichu : 
		/// </summary>
		[EnumTextValue("GHICHU")]
		[ColumnEnum("GHICHU", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Ghichu = 5
	}//End enum

	#endregion DmlopColumn Enum

} // end namespace
