using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'ADMIN_GROUPS' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAdminGroups 
	{
		/// <summary>			
		/// ID_GROUP : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ADMIN_GROUPS"</remarks>
		System.String IdGroup { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalIdGroup { get; set; }
			
		
		
		/// <summary>
		/// GROUP_NAME : 
		/// </summary>
		System.String  GroupName  { get; set; }
		
		/// <summary>
		/// ACTIVE : 
		/// </summary>
		System.Int32?  Active  { get; set; }
		
		/// <summary>
		/// PARENT : 
		/// </summary>
		System.String  Parent  { get; set; }
		
		/// <summary>
		/// DESCRIPTION : 
		/// </summary>
		System.String  Description  { get; set; }
		
		/// <summary>
		/// MODIFIED : 
		/// </summary>
		System.DateTime?  Modified  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table adminUsersCollectionFromAdminGroupusers
		/// </summary>	
		TList<AdminUsers> AdminUsersCollection_From_AdminGroupusers { get; set; }	

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table adminMenusCollectionFromAdminGroupmenus
		/// </summary>	
		TList<AdminMenus> AdminMenusCollection_From_AdminGroupmenus { get; set; }	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation adminGroupmenusIdGroup
		/// </summary>	
		TList<AdminGroupmenus> AdminGroupmenusCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation adminGroupusersIdGroup
		/// </summary>	
		TList<AdminGroupusers> AdminGroupusersCollection {  get;  set;}	

		#endregion Data Properties

	}
}


