using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'ADMIN_GROUPUSERS' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAdminGroupusers 
	{
		/// <summary>			
		/// ID_GROUP : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ADMIN_GROUPUSERS"</remarks>
		System.String IdGroup { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalIdGroup { get; set; }
			
		/// <summary>			
		/// ID_USER : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ADMIN_GROUPUSERS"</remarks>
		System.String IdUser { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalIdUser { get; set; }
			
		
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


