using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'ADMIN_USERS' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAdminUsers 
	{
		/// <summary>			
		/// ID_USER : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ADMIN_USERS"</remarks>
		System.String IdUser { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalIdUser { get; set; }
			
		
		
		/// <summary>
		/// PASSWORD : 
		/// </summary>
		System.Byte[]  Password  { get; set; }
		
		/// <summary>
		/// FULL_NAME : 
		/// </summary>
		System.String  FullName  { get; set; }
		
		/// <summary>
		/// ACTIVE : 
		/// </summary>
		System.Int32?  Active  { get; set; }
		
		/// <summary>
		/// MODIFIED : 
		/// </summary>
		System.DateTime?  Modified  { get; set; }
		
		/// <summary>
		/// DESCRIPTION : 
		/// </summary>
		System.String  Description  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table adminGroupsCollectionFromAdminGroupusers
		/// </summary>	
		TList<AdminGroups> AdminGroupsCollection_From_AdminGroupusers { get; set; }	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation adminGroupusersIdUser
		/// </summary>	
		TList<AdminGroupusers> AdminGroupusersCollection {  get;  set;}	

		#endregion Data Properties

	}
}


