using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'DMDONVI' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IDmdonvi 
	{
		/// <summary>			
		/// ID_DONVI : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "DMDONVI"</remarks>
		System.Int32 IdDonvi { get; set; }
				
		
		
		/// <summary>
		/// MA_DONVI : 
		/// </summary>
		System.String  MaDonvi  { get; set; }
		
		/// <summary>
		/// TEN_DONVI : 
		/// </summary>
		System.String  TenDonvi  { get; set; }
		
		/// <summary>
		/// ID_DONVICHA : 
		/// </summary>
		System.Int32?  IdDonvicha  { get; set; }
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		System.String  Ghichu  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation quannhanIdDonvi
		/// </summary>	
		TList<Quannhan> QuannhanCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation dmlopIdDaidoi
		/// </summary>	
		TList<Dmlop> DmlopCollection {  get;  set;}	

		#endregion Data Properties

	}
}


