using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'DMHINHTHUCKHENTHUONG' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IDmhinhthuckhenthuong 
	{
		/// <summary>			
		/// ID_HINHTHUC_KHENTHUONG : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "DMHINHTHUCKHENTHUONG"</remarks>
		System.Int32 IdHinhthucKhenthuong { get; set; }
				
		
		
		/// <summary>
		/// HINHTHUC_KHENTHUONG : 
		/// </summary>
		System.String  HinhthucKhenthuong  { get; set; }
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		System.String  Ghichu  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation lskhenthuongIdHinhthucKhenthuong
		/// </summary>	
		TList<Lskhenthuong> LskhenthuongCollection {  get;  set;}	

		#endregion Data Properties

	}
}


