using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'DMTONGIAO' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IDmtongiao 
	{
		/// <summary>			
		/// ID_TONGIAO : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "DMTONGIAO"</remarks>
		System.Int32 IdTongiao { get; set; }
				
		
		
		/// <summary>
		/// TONGIAO : 
		/// </summary>
		System.String  Tongiao  { get; set; }
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		System.String  Ghichu  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation quannhanIdTongiao
		/// </summary>	
		TList<Quannhan> QuannhanCollection {  get;  set;}	

		#endregion Data Properties

	}
}


