using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'LSKYLUAT' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ILskyluat 
	{
		/// <summary>			
		/// ID_LICHSUKYLUAT : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "LSKYLUAT"</remarks>
		System.Int64 IdLichsukyluat { get; set; }
				
		
		
		/// <summary>
		/// ID_QUANNHAN : 
		/// </summary>
		System.Int32  IdQuannhan  { get; set; }
		
		/// <summary>
		/// ID_HINHTHUC_KYLUAT : 
		/// </summary>
		System.Int32  IdHinhthucKyluat  { get; set; }
		
		/// <summary>
		/// CAP_KYLUAT : 
		/// </summary>
		System.String  CapKyluat  { get; set; }
		
		/// <summary>
		/// NGAY_QUYETDINH : 
		/// </summary>
		System.DateTime?  NgayQuyetdinh  { get; set; }
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		System.String  Ghichu  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


