using System;
using System.ComponentModel;

namespace QUANLYQN.Entities
{
	/// <summary>
	///		The data structure representation of the 'LSTRUONGLOP' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ILstruonglop 
	{
		/// <summary>			
		/// ID_LICHSUTRUONGLOP : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "LSTRUONGLOP"</remarks>
		System.Int64 IdLichsutruonglop { get; set; }
				
		
		
		/// <summary>
		/// ID_QUANNHAN : 
		/// </summary>
		System.Int32  IdQuannhan  { get; set; }
		
		/// <summary>
		/// ID_TRUONG : 
		/// </summary>
		System.Int32  IdTruong  { get; set; }
		
		/// <summary>
		/// ID_CAPHOC : 
		/// </summary>
		System.Int32  IdCaphoc  { get; set; }
		
		/// <summary>
		/// NGANHHOC : 
		/// </summary>
		System.String  Nganhhoc  { get; set; }
		
		/// <summary>
		/// THOIGIAN_BATDAU : 
		/// </summary>
		System.DateTime?  ThoigianBatdau  { get; set; }
		
		/// <summary>
		/// THOIGIAN_KETTHUC : 
		/// </summary>
		System.DateTime?  ThoigianKetthuc  { get; set; }
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		System.String  Ghichu  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


