
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Lskyluat.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace QUANLYQN.Entities
{
	///<summary>
	/// An object representation of the 'LSKYLUAT' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class LskyluatBase : EntityBase, QUANLYQN.Entities.ILskyluat, IEntityId<LskyluatKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private LskyluatEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private LskyluatEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private LskyluatEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Lskyluat> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event LskyluatEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event LskyluatEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="LskyluatBase"/> instance.
		///</summary>
		public LskyluatBase()
		{
			this.entityData = new LskyluatEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="LskyluatBase"/> instance.
		///</summary>
		///<param name="idQuannhan"></param>
		///<param name="idHinhthucKyluat"></param>
		///<param name="capKyluat"></param>
		///<param name="ngayQuyetdinh"></param>
		///<param name="ghichu"></param>
		public LskyluatBase(System.Int32 idQuannhan, System.Int32 idHinhthucKyluat, System.String capKyluat, 
			System.DateTime? ngayQuyetdinh, System.String ghichu)
		{
			this.entityData = new LskyluatEntityData();
			this.backupData = null;

			this.IdQuannhan = idQuannhan;
			this.IdHinhthucKyluat = idHinhthucKyluat;
			this.CapKyluat = capKyluat;
			this.NgayQuyetdinh = ngayQuyetdinh;
			this.Ghichu = ghichu;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Lskyluat"/> instance.
		///</summary>
		///<param name="idQuannhan"></param>
		///<param name="idHinhthucKyluat"></param>
		///<param name="capKyluat"></param>
		///<param name="ngayQuyetdinh"></param>
		///<param name="ghichu"></param>
		public static Lskyluat CreateLskyluat(System.Int32 idQuannhan, System.Int32 idHinhthucKyluat, System.String capKyluat, 
			System.DateTime? ngayQuyetdinh, System.String ghichu)
		{
			Lskyluat newLskyluat = new Lskyluat();
			newLskyluat.IdQuannhan = idQuannhan;
			newLskyluat.IdHinhthucKyluat = idHinhthucKyluat;
			newLskyluat.CapKyluat = capKyluat;
			newLskyluat.NgayQuyetdinh = ngayQuyetdinh;
			newLskyluat.Ghichu = ghichu;
			return newLskyluat;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdLichsukyluat property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 IdLichsukyluat
		{
			get
			{
				return this.entityData.IdLichsukyluat; 
			}
			
			set
			{
				if (this.entityData.IdLichsukyluat == value)
					return;
					
				OnColumnChanging(LskyluatColumn.IdLichsukyluat, this.entityData.IdLichsukyluat);
				this.entityData.IdLichsukyluat = value;
				this.EntityId.IdLichsukyluat = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LskyluatColumn.IdLichsukyluat, this.entityData.IdLichsukyluat);
				OnPropertyChanged("IdLichsukyluat");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdQuannhan property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 IdQuannhan
		{
			get
			{
				return this.entityData.IdQuannhan; 
			}
			
			set
			{
				if (this.entityData.IdQuannhan == value)
					return;
					
				OnColumnChanging(LskyluatColumn.IdQuannhan, this.entityData.IdQuannhan);
				this.entityData.IdQuannhan = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LskyluatColumn.IdQuannhan, this.entityData.IdQuannhan);
				OnPropertyChanged("IdQuannhan");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdHinhthucKyluat property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 IdHinhthucKyluat
		{
			get
			{
				return this.entityData.IdHinhthucKyluat; 
			}
			
			set
			{
				if (this.entityData.IdHinhthucKyluat == value)
					return;
					
				OnColumnChanging(LskyluatColumn.IdHinhthucKyluat, this.entityData.IdHinhthucKyluat);
				this.entityData.IdHinhthucKyluat = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LskyluatColumn.IdHinhthucKyluat, this.entityData.IdHinhthucKyluat);
				OnPropertyChanged("IdHinhthucKyluat");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CapKyluat property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String CapKyluat
		{
			get
			{
				return this.entityData.CapKyluat; 
			}
			
			set
			{
				if (this.entityData.CapKyluat == value)
					return;
					
				OnColumnChanging(LskyluatColumn.CapKyluat, this.entityData.CapKyluat);
				this.entityData.CapKyluat = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LskyluatColumn.CapKyluat, this.entityData.CapKyluat);
				OnPropertyChanged("CapKyluat");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NgayQuyetdinh property. 
		///		
		/// </summary>
		/// <value>This type is smalldatetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsNgayQuyetdinhNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? NgayQuyetdinh
		{
			get
			{
				return this.entityData.NgayQuyetdinh; 
			}
			
			set
			{
				if (this.entityData.NgayQuyetdinh == value)
					return;
					
				OnColumnChanging(LskyluatColumn.NgayQuyetdinh, this.entityData.NgayQuyetdinh);
				this.entityData.NgayQuyetdinh = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LskyluatColumn.NgayQuyetdinh, this.entityData.NgayQuyetdinh);
				OnPropertyChanged("NgayQuyetdinh");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Ghichu property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String Ghichu
		{
			get
			{
				return this.entityData.Ghichu; 
			}
			
			set
			{
				if (this.entityData.Ghichu == value)
					return;
					
				OnColumnChanging(LskyluatColumn.Ghichu, this.entityData.Ghichu);
				this.entityData.Ghichu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LskyluatColumn.Ghichu, this.entityData.Ghichu);
				OnPropertyChanged("Ghichu");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Quannhan"/>.
		/// </summary>
		/// <value>The source Quannhan for IdQuannhan.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Quannhan IdQuannhanSource
      	{
            get { return entityData.IdQuannhanSource; }
            set { entityData.IdQuannhanSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Dmhinhthuckyluat"/>.
		/// </summary>
		/// <value>The source Dmhinhthuckyluat for IdHinhthucKyluat.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Dmhinhthuckyluat IdHinhthucKyluatSource
      	{
            get { return entityData.IdHinhthucKyluatSource; }
            set { entityData.IdHinhthucKyluatSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("CapKyluat", "Cap Kyluat"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("CapKyluat", "Cap Kyluat", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "LSKYLUAT"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID_LICHSUKYLUAT", "ID_QUANNHAN", "ID_HINHTHUC_KYLUAT", "CAP_KYLUAT", "NGAY_QUYETDINH", "GHICHU"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as LskyluatEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Lskyluat) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Lskyluat>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Lskyluat);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Lskyluat Entity 
		///</summary>
		public virtual Lskyluat Copy()
		{
			//shallow copy entity
			Lskyluat copy = new Lskyluat();
			copy.SuppressEntityEvents = true;
			copy.IdLichsukyluat = this.IdLichsukyluat;
			copy.IdQuannhan = this.IdQuannhan;
			copy.IdHinhthucKyluat = this.IdHinhthucKyluat;
			copy.CapKyluat = this.CapKyluat;
			copy.NgayQuyetdinh = this.NgayQuyetdinh;
			copy.Ghichu = this.Ghichu;
			
			copy.IdQuannhanSource = MakeCopyOf(this.IdQuannhanSource) as Quannhan;
			copy.IdHinhthucKyluatSource = MakeCopyOf(this.IdHinhthucKyluatSource) as Dmhinhthuckyluat;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed Lskyluat Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Lskyluat DeepCopy()
		{
			return EntityHelper.Clone<Lskyluat>(this as Lskyluat);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as LskyluatEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as LskyluatEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(LskyluatColumn column)
		{
			switch(column)
			{
					case LskyluatColumn.IdLichsukyluat:
					return entityData.IdLichsukyluat != _originalData.IdLichsukyluat;
					case LskyluatColumn.IdQuannhan:
					return entityData.IdQuannhan != _originalData.IdQuannhan;
					case LskyluatColumn.IdHinhthucKyluat:
					return entityData.IdHinhthucKyluat != _originalData.IdHinhthucKyluat;
					case LskyluatColumn.CapKyluat:
					return entityData.CapKyluat != _originalData.CapKyluat;
					case LskyluatColumn.NgayQuyetdinh:
					return entityData.NgayQuyetdinh != _originalData.NgayQuyetdinh;
					case LskyluatColumn.Ghichu:
					return entityData.Ghichu != _originalData.Ghichu;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdLichsukyluat != _originalData.IdLichsukyluat;
			result = result || entityData.IdQuannhan != _originalData.IdQuannhan;
			result = result || entityData.IdHinhthucKyluat != _originalData.IdHinhthucKyluat;
			result = result || entityData.CapKyluat != _originalData.CapKyluat;
			result = result || entityData.NgayQuyetdinh != _originalData.NgayQuyetdinh;
			result = result || entityData.Ghichu != _originalData.Ghichu;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="LskyluatBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is LskyluatBase)
				return Equals(this, (LskyluatBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="LskyluatBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdLichsukyluat.GetHashCode() ^ 
					this.IdQuannhan.GetHashCode() ^ 
					this.IdHinhthucKyluat.GetHashCode() ^ 
					this.CapKyluat.GetHashCode() ^ 
					((this.NgayQuyetdinh == null) ? string.Empty : this.NgayQuyetdinh.ToString()).GetHashCode() ^ 
					((this.Ghichu == null) ? string.Empty : this.Ghichu.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="LskyluatBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(LskyluatBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="LskyluatBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="LskyluatBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="LskyluatBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(LskyluatBase Object1, LskyluatBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdLichsukyluat != Object2.IdLichsukyluat)
				equal = false;
			if (Object1.IdQuannhan != Object2.IdQuannhan)
				equal = false;
			if (Object1.IdHinhthucKyluat != Object2.IdHinhthucKyluat)
				equal = false;
			if (Object1.CapKyluat != Object2.CapKyluat)
				equal = false;
			if ( Object1.NgayQuyetdinh != null && Object2.NgayQuyetdinh != null )
			{
				if (Object1.NgayQuyetdinh != Object2.NgayQuyetdinh)
					equal = false;
			}
			else if (Object1.NgayQuyetdinh == null ^ Object2.NgayQuyetdinh == null )
			{
				equal = false;
			}
			if ( Object1.Ghichu != null && Object2.Ghichu != null )
			{
				if (Object1.Ghichu != Object2.Ghichu)
					equal = false;
			}
			else if (Object1.Ghichu == null ^ Object2.Ghichu == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((LskyluatBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static LskyluatComparer GetComparer()
        {
            return new LskyluatComparer();
        }
        */

        // Comparer delegates back to Lskyluat
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Lskyluat rhs, LskyluatColumn which)
        {
            switch (which)
            {
            	
            	
            	case LskyluatColumn.IdLichsukyluat:
            		return this.IdLichsukyluat.CompareTo(rhs.IdLichsukyluat);
            		
            		                 
            	
            	
            	case LskyluatColumn.IdQuannhan:
            		return this.IdQuannhan.CompareTo(rhs.IdQuannhan);
            		
            		                 
            	
            	
            	case LskyluatColumn.IdHinhthucKyluat:
            		return this.IdHinhthucKyluat.CompareTo(rhs.IdHinhthucKyluat);
            		
            		                 
            	
            	
            	case LskyluatColumn.CapKyluat:
            		return this.CapKyluat.CompareTo(rhs.CapKyluat);
            		
            		                 
            	
            	
            	case LskyluatColumn.NgayQuyetdinh:
            		return this.NgayQuyetdinh.Value.CompareTo(rhs.NgayQuyetdinh.Value);
            		
            		                 
            	
            	
            	case LskyluatColumn.Ghichu:
            		return this.Ghichu.CompareTo(rhs.Ghichu);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<LskyluatKey> Members
		
		// member variable for the EntityId property
		private LskyluatKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual LskyluatKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new LskyluatKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Lskyluat")
					.Append("|").Append( this.IdLichsukyluat.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- IdLichsukyluat: {0}{6}- IdQuannhan: {1}{6}- IdHinhthucKyluat: {2}{6}- CapKyluat: {3}{6}- NgayQuyetdinh: {4}{6}- Ghichu: {5}{6}", 
				this.IdLichsukyluat,
				this.IdQuannhan,
				this.IdHinhthucKyluat,
				this.CapKyluat,
				(this.NgayQuyetdinh == null) ? string.Empty : this.NgayQuyetdinh.ToString(),
				(this.Ghichu == null) ? string.Empty : this.Ghichu.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'LSKYLUAT' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class LskyluatEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID_LICHSUKYLUAT : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "LSKYLUAT"</remarks>
			public System.Int64 IdLichsukyluat;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ID_QUANNHAN : 
		/// </summary>
		public System.Int32		  IdQuannhan = (int)0;
		
		/// <summary>
		/// ID_HINHTHUC_KYLUAT : 
		/// </summary>
		public System.Int32		  IdHinhthucKyluat = (int)0;
		
		/// <summary>
		/// CAP_KYLUAT : 
		/// </summary>
		public System.String		  CapKyluat = string.Empty;
		
		/// <summary>
		/// NGAY_QUYETDINH : 
		/// </summary>
		public System.DateTime?		  NgayQuyetdinh = null;
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		public System.String		  Ghichu = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Quannhan _idQuannhanSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Quannhan"/>.
		/// </summary>
		/// <value>The source Quannhan for IdQuannhan.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Quannhan IdQuannhanSource
      	{
            get { return this._idQuannhanSource; }
            set { this._idQuannhanSource = value; }
      	}
		private Dmhinhthuckyluat _idHinhthucKyluatSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Dmhinhthuckyluat"/>.
		/// </summary>
		/// <value>The source Dmhinhthuckyluat for IdHinhthucKyluat.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Dmhinhthuckyluat IdHinhthucKyluatSource
      	{
            get { return this._idHinhthucKyluatSource; }
            set { this._idHinhthucKyluatSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			LskyluatEntityData _tmp = new LskyluatEntityData();
						
			_tmp.IdLichsukyluat = this.IdLichsukyluat;
			
			_tmp.IdQuannhan = this.IdQuannhan;
			_tmp.IdHinhthucKyluat = this.IdHinhthucKyluat;
			_tmp.CapKyluat = this.CapKyluat;
			_tmp.NgayQuyetdinh = this.NgayQuyetdinh;
			_tmp.Ghichu = this.Ghichu;
			
			#region Source Parent Composite Entities
			if (this.IdQuannhanSource != null)
				_tmp.IdQuannhanSource = MakeCopyOf(this.IdQuannhanSource) as Quannhan;
			if (this.IdHinhthucKyluatSource != null)
				_tmp.IdHinhthucKyluatSource = MakeCopyOf(this.IdHinhthucKyluatSource) as Dmhinhthuckyluat;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LskyluatColumn"/> which has raised the event.</param>
		public void OnColumnChanging(LskyluatColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LskyluatColumn"/> which has raised the event.</param>
		public void OnColumnChanged(LskyluatColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LskyluatColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(LskyluatColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				LskyluatEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new LskyluatEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LskyluatColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(LskyluatColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				LskyluatEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new LskyluatEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region LskyluatEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Lskyluat"/> object.
	/// </remarks>
	public class LskyluatEventArgs : System.EventArgs
	{
		private LskyluatColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the LskyluatEventArgs class.
		///</summary>
		public LskyluatEventArgs(LskyluatColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the LskyluatEventArgs class.
		///</summary>
		public LskyluatEventArgs(LskyluatColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The LskyluatColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="LskyluatColumn" />
		public LskyluatColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Lskyluat related events.
	///</summary>
	public delegate void LskyluatEventHandler(object sender, LskyluatEventArgs e);
	
	#region LskyluatComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class LskyluatComparer : System.Collections.Generic.IComparer<Lskyluat>
	{
		LskyluatColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:LskyluatComparer"/> class.
        /// </summary>
		public LskyluatComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:LskyluatComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public LskyluatComparer(LskyluatColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Lskyluat"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Lskyluat"/> to compare.</param>
        /// <param name="b">The second <c>Lskyluat</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Lskyluat a, Lskyluat b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Lskyluat entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Lskyluat a, Lskyluat b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public LskyluatColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region LskyluatKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Lskyluat"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class LskyluatKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the LskyluatKey class.
		/// </summary>
		public LskyluatKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the LskyluatKey class.
		/// </summary>
		public LskyluatKey(LskyluatBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdLichsukyluat = entity.IdLichsukyluat;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the LskyluatKey class.
		/// </summary>
		public LskyluatKey(System.Int64 idLichsukyluat)
		{
			#region Init Properties

			this.IdLichsukyluat = idLichsukyluat;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private LskyluatBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public LskyluatBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdLichsukyluat property
		private System.Int64 _idLichsukyluat;
		
		/// <summary>
		/// Gets or sets the IdLichsukyluat property.
		/// </summary>
		public System.Int64 IdLichsukyluat
		{
			get { return _idLichsukyluat; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdLichsukyluat = value;
				
				_idLichsukyluat = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdLichsukyluat = ( values["IdLichsukyluat"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["IdLichsukyluat"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdLichsukyluat", IdLichsukyluat);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdLichsukyluat: {0}{1}",
								IdLichsukyluat,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region LskyluatColumn Enum
	
	/// <summary>
	/// Enumerate the Lskyluat columns.
	/// </summary>
	[Serializable]
	public enum LskyluatColumn : int
	{
		/// <summary>
		/// IdLichsukyluat : 
		/// </summary>
		[EnumTextValue("ID_LICHSUKYLUAT")]
		[ColumnEnum("ID_LICHSUKYLUAT", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		IdLichsukyluat = 1,
		/// <summary>
		/// IdQuannhan : 
		/// </summary>
		[EnumTextValue("ID_QUANNHAN")]
		[ColumnEnum("ID_QUANNHAN", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		IdQuannhan = 2,
		/// <summary>
		/// IdHinhthucKyluat : 
		/// </summary>
		[EnumTextValue("ID_HINHTHUC_KYLUAT")]
		[ColumnEnum("ID_HINHTHUC_KYLUAT", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		IdHinhthucKyluat = 3,
		/// <summary>
		/// CapKyluat : 
		/// </summary>
		[EnumTextValue("CAP_KYLUAT")]
		[ColumnEnum("CAP_KYLUAT", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		CapKyluat = 4,
		/// <summary>
		/// NgayQuyetdinh : 
		/// </summary>
		[EnumTextValue("NGAY_QUYETDINH")]
		[ColumnEnum("NGAY_QUYETDINH", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		NgayQuyetdinh = 5,
		/// <summary>
		/// Ghichu : 
		/// </summary>
		[EnumTextValue("GHICHU")]
		[ColumnEnum("GHICHU", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Ghichu = 6
	}//End enum

	#endregion LskyluatColumn Enum

} // end namespace
