
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Lstruonglop.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace QUANLYQN.Entities
{
	///<summary>
	/// An object representation of the 'LSTRUONGLOP' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class LstruonglopBase : EntityBase, QUANLYQN.Entities.ILstruonglop, IEntityId<LstruonglopKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private LstruonglopEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private LstruonglopEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private LstruonglopEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Lstruonglop> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event LstruonglopEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event LstruonglopEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="LstruonglopBase"/> instance.
		///</summary>
		public LstruonglopBase()
		{
			this.entityData = new LstruonglopEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="LstruonglopBase"/> instance.
		///</summary>
		///<param name="idQuannhan"></param>
		///<param name="idTruong"></param>
		///<param name="idCaphoc"></param>
		///<param name="nganhhoc"></param>
		///<param name="thoigianBatdau"></param>
		///<param name="thoigianKetthuc"></param>
		///<param name="ghichu"></param>
		public LstruonglopBase(System.Int32 idQuannhan, System.Int32 idTruong, System.Int32 idCaphoc, 
			System.String nganhhoc, System.DateTime? thoigianBatdau, System.DateTime? thoigianKetthuc, 
			System.String ghichu)
		{
			this.entityData = new LstruonglopEntityData();
			this.backupData = null;

			this.IdQuannhan = idQuannhan;
			this.IdTruong = idTruong;
			this.IdCaphoc = idCaphoc;
			this.Nganhhoc = nganhhoc;
			this.ThoigianBatdau = thoigianBatdau;
			this.ThoigianKetthuc = thoigianKetthuc;
			this.Ghichu = ghichu;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Lstruonglop"/> instance.
		///</summary>
		///<param name="idQuannhan"></param>
		///<param name="idTruong"></param>
		///<param name="idCaphoc"></param>
		///<param name="nganhhoc"></param>
		///<param name="thoigianBatdau"></param>
		///<param name="thoigianKetthuc"></param>
		///<param name="ghichu"></param>
		public static Lstruonglop CreateLstruonglop(System.Int32 idQuannhan, System.Int32 idTruong, System.Int32 idCaphoc, 
			System.String nganhhoc, System.DateTime? thoigianBatdau, System.DateTime? thoigianKetthuc, 
			System.String ghichu)
		{
			Lstruonglop newLstruonglop = new Lstruonglop();
			newLstruonglop.IdQuannhan = idQuannhan;
			newLstruonglop.IdTruong = idTruong;
			newLstruonglop.IdCaphoc = idCaphoc;
			newLstruonglop.Nganhhoc = nganhhoc;
			newLstruonglop.ThoigianBatdau = thoigianBatdau;
			newLstruonglop.ThoigianKetthuc = thoigianKetthuc;
			newLstruonglop.Ghichu = ghichu;
			return newLstruonglop;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdLichsutruonglop property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 IdLichsutruonglop
		{
			get
			{
				return this.entityData.IdLichsutruonglop; 
			}
			
			set
			{
				if (this.entityData.IdLichsutruonglop == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.IdLichsutruonglop, this.entityData.IdLichsutruonglop);
				this.entityData.IdLichsutruonglop = value;
				this.EntityId.IdLichsutruonglop = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.IdLichsutruonglop, this.entityData.IdLichsutruonglop);
				OnPropertyChanged("IdLichsutruonglop");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdQuannhan property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 IdQuannhan
		{
			get
			{
				return this.entityData.IdQuannhan; 
			}
			
			set
			{
				if (this.entityData.IdQuannhan == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.IdQuannhan, this.entityData.IdQuannhan);
				this.entityData.IdQuannhan = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.IdQuannhan, this.entityData.IdQuannhan);
				OnPropertyChanged("IdQuannhan");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdTruong property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 IdTruong
		{
			get
			{
				return this.entityData.IdTruong; 
			}
			
			set
			{
				if (this.entityData.IdTruong == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.IdTruong, this.entityData.IdTruong);
				this.entityData.IdTruong = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.IdTruong, this.entityData.IdTruong);
				OnPropertyChanged("IdTruong");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdCaphoc property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 IdCaphoc
		{
			get
			{
				return this.entityData.IdCaphoc; 
			}
			
			set
			{
				if (this.entityData.IdCaphoc == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.IdCaphoc, this.entityData.IdCaphoc);
				this.entityData.IdCaphoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.IdCaphoc, this.entityData.IdCaphoc);
				OnPropertyChanged("IdCaphoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Nganhhoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Nganhhoc
		{
			get
			{
				return this.entityData.Nganhhoc; 
			}
			
			set
			{
				if (this.entityData.Nganhhoc == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.Nganhhoc, this.entityData.Nganhhoc);
				this.entityData.Nganhhoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.Nganhhoc, this.entityData.Nganhhoc);
				OnPropertyChanged("Nganhhoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ThoigianBatdau property. 
		///		
		/// </summary>
		/// <value>This type is smalldatetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsThoigianBatdauNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ThoigianBatdau
		{
			get
			{
				return this.entityData.ThoigianBatdau; 
			}
			
			set
			{
				if (this.entityData.ThoigianBatdau == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.ThoigianBatdau, this.entityData.ThoigianBatdau);
				this.entityData.ThoigianBatdau = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.ThoigianBatdau, this.entityData.ThoigianBatdau);
				OnPropertyChanged("ThoigianBatdau");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ThoigianKetthuc property. 
		///		
		/// </summary>
		/// <value>This type is smalldatetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsThoigianKetthucNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ThoigianKetthuc
		{
			get
			{
				return this.entityData.ThoigianKetthuc; 
			}
			
			set
			{
				if (this.entityData.ThoigianKetthuc == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.ThoigianKetthuc, this.entityData.ThoigianKetthuc);
				this.entityData.ThoigianKetthuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.ThoigianKetthuc, this.entityData.ThoigianKetthuc);
				OnPropertyChanged("ThoigianKetthuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Ghichu property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String Ghichu
		{
			get
			{
				return this.entityData.Ghichu; 
			}
			
			set
			{
				if (this.entityData.Ghichu == value)
					return;
					
				OnColumnChanging(LstruonglopColumn.Ghichu, this.entityData.Ghichu);
				this.entityData.Ghichu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LstruonglopColumn.Ghichu, this.entityData.Ghichu);
				OnPropertyChanged("Ghichu");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Dmtruong"/>.
		/// </summary>
		/// <value>The source Dmtruong for IdTruong.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Dmtruong IdTruongSource
      	{
            get { return entityData.IdTruongSource; }
            set { entityData.IdTruongSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Dmcaphoc"/>.
		/// </summary>
		/// <value>The source Dmcaphoc for IdCaphoc.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Dmcaphoc IdCaphocSource
      	{
            get { return entityData.IdCaphocSource; }
            set { entityData.IdCaphocSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Quannhan"/>.
		/// </summary>
		/// <value>The source Quannhan for IdQuannhan.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Quannhan IdQuannhanSource
      	{
            get { return entityData.IdQuannhanSource; }
            set { entityData.IdQuannhanSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("Nganhhoc", "Nganhhoc", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "LSTRUONGLOP"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID_LICHSUTRUONGLOP", "ID_QUANNHAN", "ID_TRUONG", "ID_CAPHOC", "NGANHHOC", "THOIGIAN_BATDAU", "THOIGIAN_KETTHUC", "GHICHU"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as LstruonglopEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Lstruonglop) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Lstruonglop>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Lstruonglop);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Lstruonglop Entity 
		///</summary>
		public virtual Lstruonglop Copy()
		{
			//shallow copy entity
			Lstruonglop copy = new Lstruonglop();
			copy.SuppressEntityEvents = true;
			copy.IdLichsutruonglop = this.IdLichsutruonglop;
			copy.IdQuannhan = this.IdQuannhan;
			copy.IdTruong = this.IdTruong;
			copy.IdCaphoc = this.IdCaphoc;
			copy.Nganhhoc = this.Nganhhoc;
			copy.ThoigianBatdau = this.ThoigianBatdau;
			copy.ThoigianKetthuc = this.ThoigianKetthuc;
			copy.Ghichu = this.Ghichu;
			
			copy.IdTruongSource = MakeCopyOf(this.IdTruongSource) as Dmtruong;
			copy.IdCaphocSource = MakeCopyOf(this.IdCaphocSource) as Dmcaphoc;
			copy.IdQuannhanSource = MakeCopyOf(this.IdQuannhanSource) as Quannhan;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed Lstruonglop Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Lstruonglop DeepCopy()
		{
			return EntityHelper.Clone<Lstruonglop>(this as Lstruonglop);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as LstruonglopEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as LstruonglopEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(LstruonglopColumn column)
		{
			switch(column)
			{
					case LstruonglopColumn.IdLichsutruonglop:
					return entityData.IdLichsutruonglop != _originalData.IdLichsutruonglop;
					case LstruonglopColumn.IdQuannhan:
					return entityData.IdQuannhan != _originalData.IdQuannhan;
					case LstruonglopColumn.IdTruong:
					return entityData.IdTruong != _originalData.IdTruong;
					case LstruonglopColumn.IdCaphoc:
					return entityData.IdCaphoc != _originalData.IdCaphoc;
					case LstruonglopColumn.Nganhhoc:
					return entityData.Nganhhoc != _originalData.Nganhhoc;
					case LstruonglopColumn.ThoigianBatdau:
					return entityData.ThoigianBatdau != _originalData.ThoigianBatdau;
					case LstruonglopColumn.ThoigianKetthuc:
					return entityData.ThoigianKetthuc != _originalData.ThoigianKetthuc;
					case LstruonglopColumn.Ghichu:
					return entityData.Ghichu != _originalData.Ghichu;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdLichsutruonglop != _originalData.IdLichsutruonglop;
			result = result || entityData.IdQuannhan != _originalData.IdQuannhan;
			result = result || entityData.IdTruong != _originalData.IdTruong;
			result = result || entityData.IdCaphoc != _originalData.IdCaphoc;
			result = result || entityData.Nganhhoc != _originalData.Nganhhoc;
			result = result || entityData.ThoigianBatdau != _originalData.ThoigianBatdau;
			result = result || entityData.ThoigianKetthuc != _originalData.ThoigianKetthuc;
			result = result || entityData.Ghichu != _originalData.Ghichu;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="LstruonglopBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is LstruonglopBase)
				return Equals(this, (LstruonglopBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="LstruonglopBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdLichsutruonglop.GetHashCode() ^ 
					this.IdQuannhan.GetHashCode() ^ 
					this.IdTruong.GetHashCode() ^ 
					this.IdCaphoc.GetHashCode() ^ 
					((this.Nganhhoc == null) ? string.Empty : this.Nganhhoc.ToString()).GetHashCode() ^ 
					((this.ThoigianBatdau == null) ? string.Empty : this.ThoigianBatdau.ToString()).GetHashCode() ^ 
					((this.ThoigianKetthuc == null) ? string.Empty : this.ThoigianKetthuc.ToString()).GetHashCode() ^ 
					((this.Ghichu == null) ? string.Empty : this.Ghichu.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="LstruonglopBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(LstruonglopBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="LstruonglopBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="LstruonglopBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="LstruonglopBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(LstruonglopBase Object1, LstruonglopBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdLichsutruonglop != Object2.IdLichsutruonglop)
				equal = false;
			if (Object1.IdQuannhan != Object2.IdQuannhan)
				equal = false;
			if (Object1.IdTruong != Object2.IdTruong)
				equal = false;
			if (Object1.IdCaphoc != Object2.IdCaphoc)
				equal = false;
			if ( Object1.Nganhhoc != null && Object2.Nganhhoc != null )
			{
				if (Object1.Nganhhoc != Object2.Nganhhoc)
					equal = false;
			}
			else if (Object1.Nganhhoc == null ^ Object2.Nganhhoc == null )
			{
				equal = false;
			}
			if ( Object1.ThoigianBatdau != null && Object2.ThoigianBatdau != null )
			{
				if (Object1.ThoigianBatdau != Object2.ThoigianBatdau)
					equal = false;
			}
			else if (Object1.ThoigianBatdau == null ^ Object2.ThoigianBatdau == null )
			{
				equal = false;
			}
			if ( Object1.ThoigianKetthuc != null && Object2.ThoigianKetthuc != null )
			{
				if (Object1.ThoigianKetthuc != Object2.ThoigianKetthuc)
					equal = false;
			}
			else if (Object1.ThoigianKetthuc == null ^ Object2.ThoigianKetthuc == null )
			{
				equal = false;
			}
			if ( Object1.Ghichu != null && Object2.Ghichu != null )
			{
				if (Object1.Ghichu != Object2.Ghichu)
					equal = false;
			}
			else if (Object1.Ghichu == null ^ Object2.Ghichu == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((LstruonglopBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static LstruonglopComparer GetComparer()
        {
            return new LstruonglopComparer();
        }
        */

        // Comparer delegates back to Lstruonglop
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Lstruonglop rhs, LstruonglopColumn which)
        {
            switch (which)
            {
            	
            	
            	case LstruonglopColumn.IdLichsutruonglop:
            		return this.IdLichsutruonglop.CompareTo(rhs.IdLichsutruonglop);
            		
            		                 
            	
            	
            	case LstruonglopColumn.IdQuannhan:
            		return this.IdQuannhan.CompareTo(rhs.IdQuannhan);
            		
            		                 
            	
            	
            	case LstruonglopColumn.IdTruong:
            		return this.IdTruong.CompareTo(rhs.IdTruong);
            		
            		                 
            	
            	
            	case LstruonglopColumn.IdCaphoc:
            		return this.IdCaphoc.CompareTo(rhs.IdCaphoc);
            		
            		                 
            	
            	
            	case LstruonglopColumn.Nganhhoc:
            		return this.Nganhhoc.CompareTo(rhs.Nganhhoc);
            		
            		                 
            	
            	
            	case LstruonglopColumn.ThoigianBatdau:
            		return this.ThoigianBatdau.Value.CompareTo(rhs.ThoigianBatdau.Value);
            		
            		                 
            	
            	
            	case LstruonglopColumn.ThoigianKetthuc:
            		return this.ThoigianKetthuc.Value.CompareTo(rhs.ThoigianKetthuc.Value);
            		
            		                 
            	
            	
            	case LstruonglopColumn.Ghichu:
            		return this.Ghichu.CompareTo(rhs.Ghichu);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<LstruonglopKey> Members
		
		// member variable for the EntityId property
		private LstruonglopKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual LstruonglopKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new LstruonglopKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Lstruonglop")
					.Append("|").Append( this.IdLichsutruonglop.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- IdLichsutruonglop: {0}{8}- IdQuannhan: {1}{8}- IdTruong: {2}{8}- IdCaphoc: {3}{8}- Nganhhoc: {4}{8}- ThoigianBatdau: {5}{8}- ThoigianKetthuc: {6}{8}- Ghichu: {7}{8}", 
				this.IdLichsutruonglop,
				this.IdQuannhan,
				this.IdTruong,
				this.IdCaphoc,
				(this.Nganhhoc == null) ? string.Empty : this.Nganhhoc.ToString(),
				(this.ThoigianBatdau == null) ? string.Empty : this.ThoigianBatdau.ToString(),
				(this.ThoigianKetthuc == null) ? string.Empty : this.ThoigianKetthuc.ToString(),
				(this.Ghichu == null) ? string.Empty : this.Ghichu.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'LSTRUONGLOP' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class LstruonglopEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID_LICHSUTRUONGLOP : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "LSTRUONGLOP"</remarks>
			public System.Int64 IdLichsutruonglop;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ID_QUANNHAN : 
		/// </summary>
		public System.Int32		  IdQuannhan = (int)0;
		
		/// <summary>
		/// ID_TRUONG : 
		/// </summary>
		public System.Int32		  IdTruong = (int)0;
		
		/// <summary>
		/// ID_CAPHOC : 
		/// </summary>
		public System.Int32		  IdCaphoc = (int)0;
		
		/// <summary>
		/// NGANHHOC : 
		/// </summary>
		public System.String		  Nganhhoc = null;
		
		/// <summary>
		/// THOIGIAN_BATDAU : 
		/// </summary>
		public System.DateTime?		  ThoigianBatdau = null;
		
		/// <summary>
		/// THOIGIAN_KETTHUC : 
		/// </summary>
		public System.DateTime?		  ThoigianKetthuc = null;
		
		/// <summary>
		/// GHICHU : 
		/// </summary>
		public System.String		  Ghichu = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Dmtruong _idTruongSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Dmtruong"/>.
		/// </summary>
		/// <value>The source Dmtruong for IdTruong.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Dmtruong IdTruongSource
      	{
            get { return this._idTruongSource; }
            set { this._idTruongSource = value; }
      	}
		private Dmcaphoc _idCaphocSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Dmcaphoc"/>.
		/// </summary>
		/// <value>The source Dmcaphoc for IdCaphoc.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Dmcaphoc IdCaphocSource
      	{
            get { return this._idCaphocSource; }
            set { this._idCaphocSource = value; }
      	}
		private Quannhan _idQuannhanSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Quannhan"/>.
		/// </summary>
		/// <value>The source Quannhan for IdQuannhan.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Quannhan IdQuannhanSource
      	{
            get { return this._idQuannhanSource; }
            set { this._idQuannhanSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			LstruonglopEntityData _tmp = new LstruonglopEntityData();
						
			_tmp.IdLichsutruonglop = this.IdLichsutruonglop;
			
			_tmp.IdQuannhan = this.IdQuannhan;
			_tmp.IdTruong = this.IdTruong;
			_tmp.IdCaphoc = this.IdCaphoc;
			_tmp.Nganhhoc = this.Nganhhoc;
			_tmp.ThoigianBatdau = this.ThoigianBatdau;
			_tmp.ThoigianKetthuc = this.ThoigianKetthuc;
			_tmp.Ghichu = this.Ghichu;
			
			#region Source Parent Composite Entities
			if (this.IdTruongSource != null)
				_tmp.IdTruongSource = MakeCopyOf(this.IdTruongSource) as Dmtruong;
			if (this.IdCaphocSource != null)
				_tmp.IdCaphocSource = MakeCopyOf(this.IdCaphocSource) as Dmcaphoc;
			if (this.IdQuannhanSource != null)
				_tmp.IdQuannhanSource = MakeCopyOf(this.IdQuannhanSource) as Quannhan;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LstruonglopColumn"/> which has raised the event.</param>
		public void OnColumnChanging(LstruonglopColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LstruonglopColumn"/> which has raised the event.</param>
		public void OnColumnChanged(LstruonglopColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LstruonglopColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(LstruonglopColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				LstruonglopEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new LstruonglopEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LstruonglopColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(LstruonglopColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				LstruonglopEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new LstruonglopEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region LstruonglopEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Lstruonglop"/> object.
	/// </remarks>
	public class LstruonglopEventArgs : System.EventArgs
	{
		private LstruonglopColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the LstruonglopEventArgs class.
		///</summary>
		public LstruonglopEventArgs(LstruonglopColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the LstruonglopEventArgs class.
		///</summary>
		public LstruonglopEventArgs(LstruonglopColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The LstruonglopColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="LstruonglopColumn" />
		public LstruonglopColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Lstruonglop related events.
	///</summary>
	public delegate void LstruonglopEventHandler(object sender, LstruonglopEventArgs e);
	
	#region LstruonglopComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class LstruonglopComparer : System.Collections.Generic.IComparer<Lstruonglop>
	{
		LstruonglopColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:LstruonglopComparer"/> class.
        /// </summary>
		public LstruonglopComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:LstruonglopComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public LstruonglopComparer(LstruonglopColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Lstruonglop"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Lstruonglop"/> to compare.</param>
        /// <param name="b">The second <c>Lstruonglop</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Lstruonglop a, Lstruonglop b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Lstruonglop entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Lstruonglop a, Lstruonglop b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public LstruonglopColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region LstruonglopKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Lstruonglop"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class LstruonglopKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the LstruonglopKey class.
		/// </summary>
		public LstruonglopKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the LstruonglopKey class.
		/// </summary>
		public LstruonglopKey(LstruonglopBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdLichsutruonglop = entity.IdLichsutruonglop;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the LstruonglopKey class.
		/// </summary>
		public LstruonglopKey(System.Int64 idLichsutruonglop)
		{
			#region Init Properties

			this.IdLichsutruonglop = idLichsutruonglop;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private LstruonglopBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public LstruonglopBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdLichsutruonglop property
		private System.Int64 _idLichsutruonglop;
		
		/// <summary>
		/// Gets or sets the IdLichsutruonglop property.
		/// </summary>
		public System.Int64 IdLichsutruonglop
		{
			get { return _idLichsutruonglop; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdLichsutruonglop = value;
				
				_idLichsutruonglop = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdLichsutruonglop = ( values["IdLichsutruonglop"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["IdLichsutruonglop"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdLichsutruonglop", IdLichsutruonglop);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdLichsutruonglop: {0}{1}",
								IdLichsutruonglop,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region LstruonglopColumn Enum
	
	/// <summary>
	/// Enumerate the Lstruonglop columns.
	/// </summary>
	[Serializable]
	public enum LstruonglopColumn : int
	{
		/// <summary>
		/// IdLichsutruonglop : 
		/// </summary>
		[EnumTextValue("ID_LICHSUTRUONGLOP")]
		[ColumnEnum("ID_LICHSUTRUONGLOP", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		IdLichsutruonglop = 1,
		/// <summary>
		/// IdQuannhan : 
		/// </summary>
		[EnumTextValue("ID_QUANNHAN")]
		[ColumnEnum("ID_QUANNHAN", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		IdQuannhan = 2,
		/// <summary>
		/// IdTruong : 
		/// </summary>
		[EnumTextValue("ID_TRUONG")]
		[ColumnEnum("ID_TRUONG", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		IdTruong = 3,
		/// <summary>
		/// IdCaphoc : 
		/// </summary>
		[EnumTextValue("ID_CAPHOC")]
		[ColumnEnum("ID_CAPHOC", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		IdCaphoc = 4,
		/// <summary>
		/// Nganhhoc : 
		/// </summary>
		[EnumTextValue("NGANHHOC")]
		[ColumnEnum("NGANHHOC", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Nganhhoc = 5,
		/// <summary>
		/// ThoigianBatdau : 
		/// </summary>
		[EnumTextValue("THOIGIAN_BATDAU")]
		[ColumnEnum("THOIGIAN_BATDAU", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ThoigianBatdau = 6,
		/// <summary>
		/// ThoigianKetthuc : 
		/// </summary>
		[EnumTextValue("THOIGIAN_KETTHUC")]
		[ColumnEnum("THOIGIAN_KETTHUC", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ThoigianKetthuc = 7,
		/// <summary>
		/// Ghichu : 
		/// </summary>
		[EnumTextValue("GHICHU")]
		[ColumnEnum("GHICHU", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Ghichu = 8
	}//End enum

	#endregion LstruonglopColumn Enum

} // end namespace
